[package]
name = "audioipc-client"
version = "0.4.0"
authors = [
        "Matthew Gregan <kinetik@flim.org>",
        "Dan Glastonbury <dan.glastonbury@gmail.com>"
        ]
description = "Cubeb Backend for talking to remote cubeb server."
edition = "2018"

[dependencies]
audioipc = { path="../audioipc" }
cubeb-backend = "0.5.5"
futures = { version="0.3.15", default-features=false, features=["std"] }
futures-cpupool = { version="0.1.8", default-features=false }
log = "0.4"
tokio = "0.1"
audio_thread_priority = "0.15.0"
lazy_static = "1.2.0"
cfg-if = "0.1.0"
